# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b821f029cde7e61442eb77e79bb70b5f39c78a96e9c1a3e5ad1e5cd1f74cc8f77b54e95ae2e71d9a8ddb5ccc65f529805895696d98e671dcff7080e8f00e0c02

test:
  secret_key_base: 5a425991165d406c488ca885cfa10e19648fa9c011c3252eaffc3fa3df47f5b3e22ec3fbe0a31e113dc65b30952b944cdc3d28262c96ce724e03316cb48bd7c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
